version: '3'

interval: '200ms'

tasks:
  templates:
    sources:
      - '**/*.templ'
    cmds:
      - templ generate
  build:
    sources:
      - '**/*.go'
    cmds:
      - go build -o bin/go-ecommerce server.go
      - task: run
  run:
    cmds:
      - ./bin/go-ecommerce
  watch:
    watch: true
    deps: [build, templates]
    cmds:
      - task: run
