// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "fregoli.dev/go-ecommerce/types"

func Head(data types.Data) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<meta charset=\"utf-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Go eCommerce</title><!-- Fonts --><link type=\"text/css\" rel=\"stylesheet\" href=\"/assets/styles/fonts.css\"><!-- Bootstrap --><link type=\"text/css\" rel=\"stylesheet\" href=\"/assets/styles/bootstrap.min.css\"><!-- Slick --><link type=\"text/css\" rel=\"stylesheet\" href=\"/assets/styles/slick.css\"><link type=\"text/css\" rel=\"stylesheet\" href=\"/assets/styles/slick-theme.css\"><!-- nouislider --><link type=\"text/css\" rel=\"stylesheet\" href=\"/assets/styles/nouislider.min.css\"><!-- Font Awesome Icon --><link rel=\"stylesheet\" href=\"/assets/styles/font-awesome.min.css\"><!-- Custom stlylesheet --><link type=\"text/css\" rel=\"stylesheet\" href=\"/assets/styles/style.css\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
