//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Brand = newBrandTable("", "brand", "")

type brandTable struct {
	sqlite.Table

	// Columns
	ID   sqlite.ColumnInteger
	Slug sqlite.ColumnString
	Name sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type BrandTable struct {
	brandTable

	EXCLUDED brandTable
}

// AS creates new BrandTable with assigned alias
func (a BrandTable) AS(alias string) *BrandTable {
	return newBrandTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BrandTable with assigned schema name
func (a BrandTable) FromSchema(schemaName string) *BrandTable {
	return newBrandTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BrandTable with assigned table prefix
func (a BrandTable) WithPrefix(prefix string) *BrandTable {
	return newBrandTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BrandTable with assigned table suffix
func (a BrandTable) WithSuffix(suffix string) *BrandTable {
	return newBrandTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBrandTable(schemaName, tableName, alias string) *BrandTable {
	return &BrandTable{
		brandTable: newBrandTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newBrandTableImpl("", "excluded", ""),
	}
}

func newBrandTableImpl(schemaName, tableName, alias string) brandTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		SlugColumn     = sqlite.StringColumn("slug")
		NameColumn     = sqlite.StringColumn("name")
		allColumns     = sqlite.ColumnList{IDColumn, SlugColumn, NameColumn}
		mutableColumns = sqlite.ColumnList{SlugColumn, NameColumn}
	)

	return brandTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Slug: SlugColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
