//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Wishlist = newWishlistTable("", "wishlist", "")

type wishlistTable struct {
	sqlite.Table

	// Columns
	User    sqlite.ColumnInteger
	Product sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type WishlistTable struct {
	wishlistTable

	EXCLUDED wishlistTable
}

// AS creates new WishlistTable with assigned alias
func (a WishlistTable) AS(alias string) *WishlistTable {
	return newWishlistTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new WishlistTable with assigned schema name
func (a WishlistTable) FromSchema(schemaName string) *WishlistTable {
	return newWishlistTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new WishlistTable with assigned table prefix
func (a WishlistTable) WithPrefix(prefix string) *WishlistTable {
	return newWishlistTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new WishlistTable with assigned table suffix
func (a WishlistTable) WithSuffix(suffix string) *WishlistTable {
	return newWishlistTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newWishlistTable(schemaName, tableName, alias string) *WishlistTable {
	return &WishlistTable{
		wishlistTable: newWishlistTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newWishlistTableImpl("", "excluded", ""),
	}
}

func newWishlistTableImpl(schemaName, tableName, alias string) wishlistTable {
	var (
		UserColumn     = sqlite.IntegerColumn("user")
		ProductColumn  = sqlite.IntegerColumn("product")
		allColumns     = sqlite.ColumnList{UserColumn, ProductColumn}
		mutableColumns = sqlite.ColumnList{}
	)

	return wishlistTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		User:    UserColumn,
		Product: ProductColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
